language: python

python:
    - 2.7

before_install:
    #Clean up some space (using aptitude to remove as it is less strict if it doesn't find the package that wants to remove)
    - sudo apt-get install -y aptitude
    - sudo apt-get clean
    - sudo aptitude purge -q -y ruby mysql-common mysql-client mysql-server emacs python2.5 python2.6 python3.1 python3.2 postgresql-common postgresql-client postgresql-server-dev-all sqlite3 mongodb-10gen redis-server elasticsearch erlang-base libcairo2 libcairo2-dev xserver-xorg-core x11-utils x11-common
    - sudo apt-get autoremove
    - sudo rm -rf /usr/share/doc

install:
    - sudo apt-get update
    - sudo apt-get install -q -y python-software-properties
    - sudo add-apt-repository -y ppa:scilifelab/scilifelab
    - sudo add-apt-repository -y ppa:debian-med/ppa
    - sudo apt-get update
    - sudo apt-get install -q -y git-core gcc picard-tools bowtie bwa freebayes snpeff-2 fastqc-0.10.1 gatk r-base tophat openjdk-6-jre samtools unzip lftp cufflinks wigtools
    #Download snpeff gnome database
    - lftp -e 'pget -n 8 http://downloads.sourceforge.net/project/snpeff/databases/v2_0_5/snpEff_v2_0_5_GRCh37.63.zip; quit'
    - sudo unzip snpEff_v2_0_5_GRCh37.63.zip -d /usr/share/snpEff/ && rm snpEff_v2_0_5_GRCh37.63.zip
    - sudo pip install numpy
    - cd nextgen && sudo python setup.py install

notifications:
    email: false

before_script:
    - cd tests
    #Export some environment variables
    - export PICARD_HOME=/usr/share/java/picard
    - export SNPEFF_HOME=/usr/share/java/snpeff
    - export GATK_HOME=/usr/share/java/gatk

script: nosetests -s -v --with-xunit -a standard
